modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="createjeicompat"
version="1.0.3-beta"
displayName="Create JEI Compat"
authors="Starion"
description='''JEI compatibility mod for Create mod with enhanced sequenced assembly display'''

[[dependencies.createjeicompat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.createjeicompat]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createjeicompat]]
modId="jei"
mandatory=true
versionRange="[15.0.0,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="createjeicompat.mixins.json"
